export const CONFIG = {
    siteDescription: "Calori Sync is a calorie tracking app",
    siteTitle: "Calori Sync",
    siteUrl: process.env.NEXT_PUBLIC_BUILD_URL,
    siteImage: '',
    siteKeywords: '',
    siteLanguage: 'EN',
    siteLocale: 'EN-US',
    twitterUsername: '',
    authorName: '',
    authorDescription: '',
    authorImage: '',
    authorWebsite: '',
    authorSocial: {
        twitter: '',
        facebook: '',
        linkedin: '',
        instagram: '',
        youtube: '',
        github: '',
        codepen: '',
        stackoverflow: '',
        devto: '',
        medium: '',
        rss: ''
    },
    organizationName: '',
    organizationDescription: '',
    organizationImage: '',
    organizationWebsite: '',
    organizationSocial: {
        twitter: '',
        facebook: '',
        linkedin: '',
        instagram: '',
        youtube: '',
        github: '',
        codepen: '',
        stackoverflow: '',
        devto: '',
        medium: '',
        rss: ''
    },
    googleAnalyticsId: '',
}