export const CONFIG = {
    siteDescription: "Jump start your NextJS PWA project with Chakrastic PWA",
    siteTitle: "Chakrastic PWA",
    siteUrl: process.env.NEXT_PUBLIC_BUILD_URL,
    siteImage: '',
    siteKeywords: '',
    siteLanguage: 'EN',
    siteLocale: 'EN-US',
    twitterUsername: '@micurran_dev',
    authorName: 'Michael Curran',
    authorDescription: '',
    authorImage: '',
    authorWebsite: 'https://micurran.dev',
    authorSocial: {
        twitter: '@micurran_dev',
        facebook: '',
        linkedin: 'linkedin.com/mi-curran',
        instagram: '',
        youtube: '',
        github: 'github.com/micurran',
        codepen: '',
        stackoverflow: '',
        devto: '',
        medium: '',
        rss: ''
    },
    organizationName: '',
    organizationDescription: '',
    organizationImage: '',
    organizationWebsite: '',
    organizationSocial: {
        twitter: '',
        facebook: '',
        linkedin: '',
        instagram: '',
        youtube: '',
        github: '',
        codepen: '',
        stackoverflow: '',
        devto: '',
        medium: '',
        rss: ''
    },
    googleAnalyticsId: '',
}